#pragma once

#include "packages/root/model/audio_clip.ar.h"

#include "packages/root/model/assets/asset.h"

#include <utils/buffer.h>

#include <cstdint>

namespace kryga
{
namespace root
{

// Source encoding of the bytes stored in m_data. miniaudio sniffs the format
// from the payload at decode time, so this is metadata for the editor and for
// choosing a decoding path — it is not authoritative.
//
// uint32_t underlying type is deliberate: the reflection save/load path
// round-trips uint32 as a YAML number, whereas a uint8_t (unsigned char) value
// serializes as a raw byte character that fails to load back.
enum class audio_format : uint32_t
{
    unknown = 0,
    wav = 1,
    mp3 = 2,
    flac = 3,
    ogg_vorbis = 4
};

// clang-format off
KRG_ar_class(
    "architype=audio_clip",
    mcp_schema = "string:asset_id",
    mcp_hint   = "Encoded audio sample [WAV/MP3/FLAC/OGG] — decoded on load and played by the audio "
                 "system; not a GPU resource"
);
class audio_clip : public asset
// clang-format on
{
    KRG_gen_meta__audio_clip();

public:
    KRG_gen_class_meta(audio_clip, asset);
    KRG_gen_construct_params{};
    KRG_gen_meta_api;

    // Reference accessor for the encoded payload — the generated get_data()
    // returns by value (a full buffer copy), which we must avoid at runtime.
    // Metadata getters/setters (get_sample_rate, set_sample_rate, ...) are
    // generated by KRG_gen_meta__audio_clip() — do not redeclare them here.
    utils::buffer&
    get_data_buffer()
    {
        return m_data;
    }

    void
    set_data_buffer(utils::buffer& v)
    {
        m_data = v;
    }

    // Metadata is probe-derived (read_only in the editor, so the generator emits
    // no setters). These exist for the importer to record the probe results.
    void
    set_sample_rate(uint32_t v)
    {
        m_sample_rate = v;
    }

    void
    set_channels(uint32_t v)
    {
        m_channels = v;
    }

    void
    set_duration_seconds(float v)
    {
        m_duration_seconds = v;
    }

    void
    set_format(audio_format v)
    {
        m_format = v;
    }

protected:
    // clang-format off
    KRG_ar_property(
        category     = "assets",
        access       = all,
        serializable = true,
        default      = true,
        mcp_hint     = "encoded audio bytes [WAV/MP3/FLAC/OGG] — read-only at runtime"
    );
    utils::buffer m_data;
    // clang-format on

    // clang-format off
    KRG_ar_property(
        category     = "meta",
        access       = read_only,
        serializable = true,
        default      = true,
        mcp_hint     = "sample rate in Hz"
    );
    uint32_t m_sample_rate = 0;
    // clang-format on

    // clang-format off
    KRG_ar_property(
        category     = "meta",
        access       = read_only,
        serializable = true,
        default      = true,
        mcp_hint     = "number of audio channels — mono is 1 and stereo is 2"
    );
    uint32_t m_channels = 0;
    // clang-format on

    // clang-format off
    KRG_ar_property(
        category     = "meta",
        access       = read_only,
        serializable = true,
        default      = true,
        mcp_hint     = "clip length in seconds"
    );
    float m_duration_seconds = 0.0f;
    // clang-format on

    // clang-format off
    KRG_ar_property(
        category     = "meta",
        access       = read_only,
        serializable = true,
        default      = true,
        mcp_hint     = "source encoding of the payload"
    );
    audio_format m_format = audio_format::unknown;
    // clang-format on
};

}  // namespace root
}  // namespace kryga
