#pragma once

#include "packages/root/model/ui_widget.ar.h"

#include "packages/root/model/smart_object.h"

namespace kryga
{
namespace root
{

// Base class for retained-mode UI widgets. A built-in root-package type (like
// game_object) so engine libs — e.g. game_session's screen container — can own,
// tick, and serialize widgets without depending on a downstream game package.
//
// A widget is a reflected smart_object (so it participates in package / level
// serialization) but deliberately does NOT inherit from game_object_component:
// UI has no 3D transform, no world position, no frustum culling, no layer flags,
// no render-children. All widgets live in pixel space.
//
// Fields are in screen pixels with origin at the top-left of the viewport. The
// render handler converts to NDC once per update using the current viewport
// size. Property accessors (get_x/get_y/get_width/get_height/get_visible +
// setters) are generated by argen into ui_widget.ar.h.
KRG_ar_class();
class ui_widget : public smart_object
{
    KRG_gen_meta__ui_widget();

public:
    KRG_gen_class_meta(ui_widget, smart_object);

    KRG_gen_construct_params{};

    KRG_gen_meta_api;

    bool
    construct(construct_params& c);

    // Required by `invalidates=render` property setters (generated). UI widgets
    // derive from smart_object (not game_object_component), so they carry their
    // own copy of the standard render-dirty queue-once guard.
    void
    mark_render_dirty();

    // Per-frame update hook for animated widgets. Default no-op; override to drive
    // property changes (the setters already mark_render_dirty). Driven by
    // screen::tick every frame, independent of play mode (UI animates in edit mode
    // too). Deliberately separate from game_object::on_tick / level::tick.
    virtual void
    on_tick(float /*dt*/)
    {
    }

protected:
    KRG_ar_property(
        "category=Layout", "serializable=true", "access=all", "invalidates=render", "default=true");
    int32_t m_x = 0;

    KRG_ar_property(
        "category=Layout", "serializable=true", "access=all", "invalidates=render", "default=true");
    int32_t m_y = 0;

    KRG_ar_property(
        "category=Layout", "serializable=true", "access=all", "invalidates=render", "default=true");
    int32_t m_width = 100;

    KRG_ar_property(
        "category=Layout", "serializable=true", "access=all", "invalidates=render", "default=true");
    int32_t m_height = 100;

    KRG_ar_property(
        "category=Layout", "serializable=true", "access=all", "invalidates=render", "default=true");
    bool m_visible = true;
};

}  // namespace root
}  // namespace kryga
